### ISSUE TITLE
Roman (ss01) numeral don't render compact on iOS

### ISSUE THREAD

**Issue by whnr** [huertatipografica/piazzolla#19]
I have a problem with the roman numerals [on my testpage](https://whnr.de/drafts/template). They render correctly in Firefox on a desktop but not on iOS. They are not as compact as they should be.

Firefox (on linux) *as expected*:
![grafik](https://user-images.githubusercontent.com/8114817/108604641-28f23400-737d-11eb-954d-9944cb71368e.png)

Safari on iOS
<img width="231" alt="signal-2021-02-20-131241" src="https://user-images.githubusercontent.com/8114817/108604685-635bd100-737d-11eb-889b-9828fb289f85.png">

This is the relevant css that does the styling
````css
ul,
ol {
  position: relative;
  margin-left: 0;
  padding-left: 2.5em;
  list-style: none;
}

ol { counter-reset: whnr-counter; }

ol li { counter-increment: whnr-counter; }

ol li::before {
    content: counter(whnr-counter, lower-roman);
    color: var(--dim-color);
    font-feature-settings: "ss01" 1;
    position: absolute;
    width: 2.5em;
    text-align: right;
    left: -.5em;
}

````

Interestingly your [demo page](https://piazzolla.huertatipografica.com/) renders them correctly on iOS.

I did subset the font significantly:
````bash
#! /bin/sh

# Check README for general info. Understand the features with the webpage
# https://wakamaifondue.com/

FEATURES_INCLUDE="aalt,ss01,ss02,lnum,onum,pnum,tnum,smcp,case,subs,sups"

FEATURES_EXCLUDE="ss03,calt,c2cs,sinf,cpsp,ordn"

UNICODES=… # List of many character ranges that we need to keep"

pyftsubset Piazzolla/ttf/Piazzolla[opsz,wght].ttf \
           --output-file="Piazolla-whnr.woff2" \
           --flavor=woff2 \
           --layout-features+=$FEATURES_INCLUDE \
           --layout-features-=$FEATURES_EXCLUDE \
           --unicodes=$UNICODES

pyftsubset Piazzolla/ttf/Piazzolla-Italic[opsz,wght].ttf \
           --output-file="Piazolla-whnr-italic.woff2" \
           --flavor=woff2 \
           --layout-features+=$FEATURES_INCLUDE \
           --layout-features-=$FEATURES_EXCLUDE \
           --unicodes=$UNICODES

mv Piazolla-whnr.woff2 Piazolla-whnr-italic.woff2 ../static/fonts
````
